const db = require("./database/connectdb.js");
const express = require("express");
const app = express();
const signup = require("./routers/signuprouter");
const emailverify = require("./routers/emailverifyroute");
const signin = require("./routers/signinouter");
const otp = require("./routers/otpgenerate.js");
const passchange = require("./routers/passchange.js");
const mailverifyfor = require("./routers/forgetmailverify.js");
const add = require("./remroutes/addroute.js");
const fetch = require("./remroutes/fetchroute.js");
const remove = require("./remroutes/remove.js");
const autodelete = require("./remroutes/autodelete.js");
const fetchlist = require("./listroute/fetchlist.js");
const listadd = require("./listroute/addlistroute.js");
const deletelist = require("./listroute/deleteroute.js");
const changelist = require("./listroute/changeroute.js");
const dotenv = require("dotenv");
dotenv.config();
app.use(express.json());
app.use(signup);
app.use(emailverify);
app.use(signin);
app.use(otp);
app.use(passchange);
app.use(mailverifyfor);
app.use(add);
app.use(fetch);
app.use(remove);
app.use(autodelete);
app.use(listadd);
app.use(fetchlist);
app.use(deletelist);
app.use(changelist);
const serverrun = async () => {
  await db();
  console.log("DataBase Connected");
  const port = process.env.PORT || 5000;
  app.listen(port, () => console.log(`Server Running at ${port}`));
};

serverrun();
